#!/usr/bin/env python3
"""Generate a multi-turn workload (bench/run_multiturn.py): one shared system prompt made of
CHARS characters of this repository's docs (docs/**/*.md in sorted path order, each file
headed by `=== path ===`, as bench/make_long_workload.py), and conversations of fixed user
turns. Every turn resends the system prompt, the earlier turns and the server's own earlier
answers, like an agent loop or a chat client: what a prefix cache is for. Non-thinking,
greedy. The output JSON is checked in and frozen; `sources` records the files and hashes.

Usage: tools/py bench/make_multiturn_workload.py --chars 30000 --name multiturn-v1 --output bench/workloads/multiturn-v1.json"""
import sys
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYSTEM = ("You are a concise engineering assistant for the zerv project. The project's design documents follow; "
          "answer questions about them in at most three sentences.\n\n")
# 8 conversations x 4 turns: distinct topics, so the conversations share only the system prompt.
TURNS = [
    ["What is zerv, in one sentence?", "Which GPU does it target first?", "Why is no C++ allowed?", "What should I read first?"],
    ["How are benchmark reports organized?", "What must a benchmark report contain?", "Where do raw results go?", "How are regressions handled?"],
    ["What is the role of llama-server in this project?", "Is it ever used for inference in production?", "How are competitors tuned?", "Name one other competitor."],
    ["What does the verification spec require before an optimization?", "What is a golden fixture?", "What tolerance rules apply?", "Why is plausible text not enough?"],
    ["How is quantized weight data handled?", "Which quantization formats are mentioned?", "How is quality loss separated from bugs?", "What is Q4_0?"],
    ["What is the tokenizer's correctness mechanism?", "How are chat templates checked?", "What happens with unsupported templates?", "Why render the prompt server-side?"],
    ["What is the KV cache used for?", "What limits the context length?", "How is VRAM measured?", "What happens if VRAM is insufficient?"],
    ["How do I run the tests?", "Which Zig version is pinned?", "Where are third-party sources kept?", "Why are they gitignored?"],
]


def documents(chars):
    parts, sources, total = [], [], 0
    for path in sorted((ROOT/"docs").rglob("*.md")):
        rel = path.relative_to(ROOT).as_posix()
        text = path.read_text()
        chunk = f"=== {rel} ===\n{text}\n"
        take = chunk[:chars - total]
        parts.append(take)
        sources.append(dict(path=rel, sha256=hashlib.sha256(text.encode()).hexdigest(), chars_used=len(take)))
        total += len(take)
        if total >= chars: break
    return "".join(parts), sources


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--chars", type=int, required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--output", type=Path, required=True)
    a = p.parse_args()
    if a.output.exists(): raise SystemExit("refusing to overwrite a frozen workload")
    body, sources = documents(a.chars)
    workload = dict(version=1, description=f"{a.name}: a shared system prompt ({len(SYSTEM) + len(body)} characters: instructions, then "
                    f"{len(body)} characters of docs/**/*.md in sorted path order; files and hashes in `sources`) and "
                    f"{len(TURNS)} conversations of {len(TURNS[0])} user turns. Each turn resends the whole conversation with the "
                    "server's own earlier answers. Generated by bench/make_multiturn_workload.py.",
                    temperature=0, seed=1234, max_tokens=128, options={"chat_template_kwargs": {"enable_thinking": False}},
                    system=SYSTEM + body, sources=sources,
                    conversations=[dict(name=f"conv{i}", turns=t) for i, t in enumerate(TURNS)])
    a.output.write_text(json.dumps(workload, indent=1)+"\n")
    print(a.output, len(SYSTEM) + len(body), "system characters from", len(sources), "files")


if __name__ == "__main__":
    if "/bazel-out/" not in sys.executable:  # hermetic (docs/specs/hermetic-build.md)
        sys.exit(f"run it with tools/py {sys.argv[0]}: the pinned Python and packages, not {sys.executable}")
    main()
