#!/usr/bin/env python3
"""Generate a long-context needle workload (bench/run_serving.py format) from this
repository's docs: a needle sentence, then CHARS characters of docs/**/*.md in sorted
path order (each file headed by `=== path ===`), then a question. Case `needle-*` asks for
the needle (non-thinking, greedy, 64 tokens); case `decode-*` asks for a 256-token
summary of the documents. The output JSON is checked in and frozen; the description
records the source files and their hashes, so the text never has to be regenerated.

Usage: bench/make_long_workload.py --chars 215000 --name long-v2 --output bench/workloads/long-v2.json"""
import sys
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NEEDLE = "Remember this for later: the secret code word is HERON-2958, and the vault number is 314."
QUESTION = "What is the secret code word and the vault number mentioned at the start of this document? Answer in one sentence."
SUMMARY = "Summarize the main decisions recorded in the documents above as a detailed bulleted list."


def documents(chars):
    parts, sources, total = [], [], 0
    for path in sorted((ROOT/"docs").rglob("*.md")):
        rel = path.relative_to(ROOT).as_posix()
        text = path.read_text()
        chunk = f"=== {rel} ===\n{text}\n"
        take = chunk[:chars - total]
        parts.append(take)
        sources.append(dict(path=rel, sha256=hashlib.sha256(text.encode()).hexdigest(), chars_used=len(take)))
        total += len(take)
        if total >= chars: break
    return "".join(parts), sources


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--chars", type=int, required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--output", type=Path, required=True)
    a = p.parse_args()
    if a.output.exists(): raise SystemExit("refusing to overwrite a frozen workload")
    body, sources = documents(a.chars)
    nothink = {"chat_template_kwargs": {"enable_thinking": False}}
    workload = dict(version=1, description=f"{a.name}: needle sentence, then {len(body)} characters of docs/**/*.md in sorted path order "
                    "(files and hashes in `sources`), then a question. Needle answer: HERON-2958 and 314. Generated by "
                    "bench/make_long_workload.py; run with --no-prompt-cache and a context above the prompt plus max_tokens.",
                    temperature=0, seed=1234, sources=sources,
                    cases=[dict(name=f"needle-{a.name}", messages=[{"role": "user", "content": f"{NEEDLE}\n\n{body}\n\n{QUESTION}"}], max_tokens=64, options=nothink),
                           dict(name=f"decode-{a.name}", messages=[{"role": "user", "content": f"{NEEDLE}\n\n{body}\n\n{SUMMARY}"}], max_tokens=256, options=nothink)])
    a.output.write_text(json.dumps(workload, indent=1)+"\n")
    print(a.output, len(body), "characters from", len(sources), "files")


if __name__ == "__main__":
    if "/bazel-out/" not in sys.executable:  # hermetic (docs/specs/hermetic-build.md)
        sys.exit(f"run it with tools/py {sys.argv[0]}: the pinned Python and packages, not {sys.executable}")
    main()
