#!/usr/bin/env python3
"""Link-time stand-in for the Vulkan loader (docs/specs/hermetic-build.md).

  vulkan_stub.py VK_XML OUT_ZIG

Writes a Zig file exporting every core Vulkan command (features VK_VERSION_1_0..1_4 of the
`vulkan` API in the registry VK_XML: exactly what the loader exports besides its WSI
extensions). Built as a shared library with SONAME libvulkan.so.1 (//src/gpu:vulkan), it
satisfies the linker without the host's loader; at run time the dynamic linker loads the real
libvulkan.so.1 by that name. The stub is never meant to be loaded; if it is (a search path
pointing at it), every function traps instead of silently doing nothing.
"""
import sys
import xml.etree.ElementTree as ET


def main():
    registry, out = sys.argv[1:3]
    names = set()
    for feature in ET.parse(registry).getroot().findall("feature"):
        if "vulkan" not in feature.get("api", "").split(","): continue
        for require in feature.findall("require"):
            names.update(command.get("name") for command in require.findall("command"))
    if len(names) < 200: raise SystemExit(f"{registry}: only {len(names)} core commands")
    lines = ["//! Generated by tools/vulkan_stub.py from the Vulkan registry: link-time stand-in for libvulkan.so.1.", ""]
    lines += [f"export fn {name}() callconv(.c) void {{\n    @trap();\n}}" for name in sorted(names)]
    open(out, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
